spring:
#  profiles:
#    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bbangduck?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bbangduck
    password: bbangduck

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true  #Jpa show-sql 시 나오는 쿼리를 정렬해서 출력
        default_batch_fetch_size: 500  #Lazy 로딩 시 한 번에 가져올 개수 지정.
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 115MB

logging:
  level:
    bbangduck.bd.bbangduck: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: debug #spring security에 대해 어떤 메세지가 출력이 되는지 확인
  file:
    name: C:\bbangduck\logs\local.log

security:
  jwt:
    jwt-token-header: X-AUTH-TOKEN
    refresh-token-expired-date: 14
    secret-key: bbangduck-jwt-secret-key
    token-valid-second: 30000
file:
  storage:
    original-image-width: 1080
    original-image-height: 720
    thumbnail-image-width: 300
    thumbnail-image-height: 300
    file-cache-second: 60
    thumbnail-prefix: s_
    upload-path: C:\bbangduck\upload

review:
  period-for-adding-surveys: 7
  perceived-theme-genres-count-limit: 5
  play-together-friends-count-limit: 5

member:
  play-inclination-top-limit: 4

social:
  sign-in:
    naver:
      client-id: _SMewO5WRZyuh6baD1d6
      client-secret: WLle0bzQ1D
      authorize-state: bbangduck7
      redirect-uri: http://localhost:8080/api/auth/naver/sign-in/callback
      request-access-token-host-uri-string: https://nid.naver.com/oauth2.0/token
      request-user-info-host-uri-string: https://openapi.naver.com/v1/nid/me
    kakao:
      native-app-key: 51a703abe9cf14386623caad48d40827
      rest-api-key: d053f45a470a5203cc53bdfb65b69c03
      java-script-key: d8952e843acd3811283f117ae4669d75
      admin-key: 1fddc4fda55b89bc7ccfc287cb305db5
      redirect-uri: http://localhost:8080/api/auth/kakao/sign-in/callback
      client-secret: R5IwQ9giaSwMLQ7Ta4gvneADq2herZzg
      authorize-state: bbangduck7
      scope: profile account_email